const mokeWaybill = [
  {
    id: "1",
    waybill_number: "0123",
    address: "Улица Путина 1",
    date: "2024-05-01",
    status: "Закрыт",
    organizations: { id: "org1", name: "Организация 1" },
    vehicle: {
      id: "wb1",
      reg_number: "123ABC",
      type: "грузовик",
      brand: "МАЗ",
      body_value: 50,
      fuel: 70,
    },
    drivers: { id: "drv1", name: "Иванов Иван", working_shift: 1 },
    owner: "Диспетчер 1",
  },
  {
    id: "2",
    waybill_number: "0456",
    address: "Улица Ленина 2",
    date: "2024-05-02",
    status: "Открыт",
    organizations: { id: "org2", name: "Организация 2" },
    vehicle: {
      id: "wb2",
      reg_number: "456XYZ",
      type: "автобус",
      brand: "ПАЗ",
      body_value: 30,
      fuel: 40,
    },
    drivers: { id: "drv2", name: "Петров Петр", working_shift: 2 },
    owner: "Диспетчер 2",
  },
  {
    id: "3",
    waybill_number: "0789",
    address: "Улица Гагарина 3",
    date: "2024-05-03",
    status: "Закрыт",
    organizations: { id: "org1", name: "Организация 1" },
    vehicle: {
      id: "wb3",
      reg_number: "789DEF",
      type: "грузовик",
      brand: "КАМАЗ",
      body_value: 60,
      fuel: 80,
    },
    drivers: { id: "drv3", name: "Сидоров Сидор", working_shift: 1 },
    owner: "Диспетчер 1",
  },
  {
    id: "4",
    waybill_number: "0101112",
    address: "Улица Кирова 4",
    date: "2024-05-04",
    status: "Открыт",
    organizations: { id: "org3", name: "Организация 3" },
    vehicle: {
      id: "wb4",
      reg_number: "101112GHI",
      type: "грузовик",
      brand: "MAN",
      body_value: 70,
      fuel: 90,
    },
    drivers: { id: "drv2", name: "Петров Петр", working_shift: 2 },
    owner: "Диспетчер 3",
  },
  {
    id: "5",
    waybill_number: "0131415",
    address: "Улица Сталина 5",
    date: "2024-05-05",
    status: "Закрыт",
    organizations: { id: "org2", name: "Организация 2" },
    vehicle: {
      id: "wb5",
      reg_number: "131415JKL",
      type: "автобус",
      brand: "ЛиАЗ",
      body_value: 40,
      fuel: 50,
    },
    drivers: { id: "drv1", name: "Иванов Иван", working_shift: 1 },
    owner: "Диспетчер 2",
  },
  {
    id: "6",
    waybill_number: "0161718",
    address: "Улица Жукова 6",
    date: "2024-05-06",
    status: "Открыт",
    organizations: { id: "org3", name: "Организация 3" },
    vehicle: {
      id: "wb6",
      reg_number: "161718MNO",
      type: "грузовик",
      brand: "Volvo",
      body_value: 80,
      fuel: 100,
    },
    drivers: { id: "drv3", name: "Сидоров Сидор", working_shift: 1 },
    owner: "Диспетчер 3",
  },
  {
    id: "7",
    waybill_number: "0192021",
    address: "Улица Космонавтов 7",
    date: "2024-05-07",
    status: "Закрыт",
    organizations: { id: "org1", name: "Организация 1" },
    vehicle: {
      id: "wb7",
      reg_number: "192021PQR",
      type: "грузовик",
      brand: "Scania",
      body_value: 90,
      fuel: 110,
    },
    drivers: { id: "drv2", name: "Петров Петр", working_shift: 2 },
    owner: "Диспетчер 1",
  },
  {
    id: "8",
    waybill_number: "0222324",
    address: "Улица Ленинградская 8",
    date: "2024-05-08",
    status: "Открыт",
    organizations: { id: "org2", name: "Организация 2" },
    vehicle: {
      id: "wb8",
      reg_number: "222324STU",
      type: "автобус",
      brand: "Mercedes",
      body_value: 50,
      fuel: 60,
    },
    drivers: { id: "drv1", name: "Иванов Иван", working_shift: 1 },
    owner: "Диспетчер 2",
  },
  {
    id: "9",
    waybill_number: "0252627",
    address: "Улица Горького 9",
    date: "2024-05-09",
    status: "Закрыт",
    organizations: { id: "org3", name: "Организация 3" },
    vehicle: {
      id: "wb9",
      reg_number: "252627VWX",
      type: "грузовик",
      brand: "DAF",
      body_value: 60,
      fuel: 70,
    },
    drivers: { id: "drv2", name: "Петров Петр", working_shift: 2 },
    owner: "Диспетчер 3",
  },
  {
    id: "10",
    waybill_number: "0282930",
    address: "Улица Большевиков 10",
    date: "2024-05-10",
    status: "Открыт",
    organizations: { id: "org1", name: "Организация 1" },
    vehicle: {
      id: "wb10",
      reg_number: "282930YZA",
      type: "автобус",
      brand: "MAN",
      body_value: 40,
      fuel: 50,
    },
    drivers: { id: "drv3", name: "Сидоров Сидор", working_shift: 1 },
    owner: "Диспетчер 1",
  },
];


export default mokeWaybill;